### PR TITLE
Fix PHP warning

### PR DESCRIPTION
**Pull request by Jako**
PHP warning: Use of undefined constant getDynaDescription

### CODE REVIEW

**Comment by BobRay** [comment]
Thanks! I can't believe I did that. ;)

**Comment by Jako** [comment]
I got a lot of log noise in one installation.

**Comment by BobRay** [comment]
Can you provide the log messages?

**Comment by Jako** [comment]
Not anymore but it contained `PHP warning: Use of undefined constant getDynaDescription`

**Pull request merged**
